# Generated by Django 4.1.6 on 2023-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("M", "Mobile"), ("TW", "Top Wear"), ("BW", "Bottom Wear")],
                max_length=2,
            ),
        ),
    ]
