# Generated by Django 4.1.6 on 2023-02-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_product_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
