# Generated by Django 4.1.6 on 2023-02-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
